/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: 'var(--surface)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        primary: 'var(--primary)',
        'primary-container': 'var(--primary-container)',
        'on-primary': 'var(--on-primary)',
        'on-primary-container': 'var(--on-primary-container)',
        secondary: 'var(--secondary)',
        'secondary-container': 'var(--secondary-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        tertiary: 'var(--tertiary)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        error: 'var(--error)',
        'error-container': 'var(--error-container)',
        'outline-variant': 'var(--outline-variant)',
        outline: 'var(--outline)',
        'focus-ring': 'var(--focus-ring)',
      },
      fontFamily: {
        headline: 'var(--font-headline)',
        body: 'var(--font-body)',
        label: 'var(--font-label)',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
